# Generated by Django 5.1.6 on 2025-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("manufacturer", models.CharField(max_length=255, verbose_name="manufacturer")),
                ("model", models.CharField(max_length=255, verbose_name="model")),
            ],
            options={
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
                "ordering": ["name"],
            },
        ),
    ]
