# Generated by Django 6.0 on 2025-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0002_alter_camera_manufacturer_alter_camera_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="camera/", verbose_name="Image"),
        ),
    ]
