# Generated by Django 6.1.1 on 2026-09-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0003_camera_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="IP"),
        ),
    ]
