# Generated by Django 6.1.1 on 2026-09-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_camera_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='door',
            field=models.BooleanField(default=False, verbose_name='Door'),
        ),
    ]
