# Generated by Django 5.1.6 on 2025-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FilePathField(verbose_name='Video file'),
        ),
    ]
