# Generated by Django 5.1.6 on 2025-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0003_alter_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(upload_to="", verbose_name="Video file"),
        ),
    ]
