# Generated by Django 5.1.6 on 2025-02-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0004_alter_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(upload_to="videos/", verbose_name="Video file"),
        ),
    ]
