# Generated by Django 5.1.6 on 2025-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0005_alter_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="camera",
            field=models.CharField(default="x", max_length=255, verbose_name="camera"),
            preserve_default=False,
        ),
    ]
