# Generated by Django 5.1.6 on 2025-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0007_alter_video_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
    ]
