# Generated by Django 5.1.6 on 2025-03-01 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
        ('video', '0008_alter_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera', verbose_name='camera'),
        ),
    ]
