# Generated by Django 5.1.6 on 2025-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0010_video_thumbnail_alter_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.FileField(null=True, upload_to="thumbnails/", verbose_name="thumbnail"),
        ),
    ]
