# Generated by Django 5.1.6 on 2025-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Duration of the video in seconds', null=True, verbose_name='duration'),
        ),
    ]
